object SinhalaMapper {
    private val mapping = mapOf(
        "k" to "ක්", "ka" to "ක", "kA" to "කැ", "kAa" to "කෑ", "ki" to "කි", "kii" to "කී", "ku" to "කු", "kuu" to "කූ", "ke" to "කෙ", "kee" to "කේ", "kY" to "ක්‍ය්", "kYa" to "ක්‍ය", "ko" to "කො", "koo" to "කෝ", "kE" to "කෛ", "kra" to "ක්‍ර", "krA" to "ක්‍රැ", "krAa" to "ක්‍රෑ", "kri" to "ක්‍රි", "krii" to "ක්‍රී", "kru" to "කෘ", "kruu" to "කෲ", "kre" to "ක්‍රෙ", "kree" to "ක්‍රේ", "kro" to "ක්‍රො", "kroo" to "ක්‍රෝ", "krE" to "ක්‍රෛ", "kau" to "කෞ",
        "g" to "ග්", "ga" to "ග", "gA" to "ගැ", "gAa" to "ගෑ", "gi" to "ගි", "gii" to "ගී", "gu" to "ගු", "guu" to "ගූ", "ge" to "ගෙ", "gee" to "ගේ", "gY" to "ග්‍ය්", "gYa" to "ග්‍ය", "go" to "ගො", "goo" to "ගෝ", "gE" to "ගෛ", "gra" to "ග්‍ර", "grA" to "ග්‍රැ", "grAa" to "ග්‍රෑ", "gri" to "ග්‍රි", "grii" to "ග්‍රී", "gru" to "ගෘ", "gruu" to "ගෲ", "gre" to "ග්‍රෙ", "gree" to "ග්‍රේ", "gro" to "ග්‍රො", "groo" to "ග්‍රෝ", "grE" to "ග්‍රෛ", "gau" to "ගෞ",
        "c" to "ච්", "ca" to "ච", "cA" to "චැ", "cAa" to "චෑ", "ci" to "චි", "cii" to "චී", "cu" to "චු", "cuu" to "චූ", "ce" to "චෙ", "cee" to "චේ", "cY" to "ච්‍ය්", "cYa" to "ච්‍ය", "co" to "චො", "coo" to "චෝ", "cE" to "චෛ", "cra" to "ච්‍ර", "crA" to "ච්‍රැ", "crAa" to "ච්‍රෑ", "cri" to "ච්‍රි", "crii" to "ච්‍රී", "cru" to "චෘ", "cruu" to "චෲ", "cre" to "ච්‍රෙ", "cree" to "ච්‍රේ", "cro" to "ච්‍රො", "croo" to "ච්‍රෝ", "crE" to "ච්‍රෛ", "cau" to "චෞ",
        "j" to "ජ්", "ja" to "ජ", "jA" to "ජැ", "jAa" to "ජෑ", "ji" to "ජි", "jii" to "ජී", "ju" to "ජු", "juu" to "ජූ", "je" to "ජෙ", "jee" to "ජේ", "jY" to "ජ්‍ය්", "jYa" to "ජ්‍ය", "jo" to "ජො", "joo" to "ජෝ", "jE" to "ජෛ", "jra" to "ජ්‍ර", "jrA" to "ජ්‍රැ", "jrAa" to "ජ්‍රෑ", "jri" to "ජ්‍රි", "jrii" to "ජ්‍රී", "jru" to "ජෘ", "jruu" to "ජෲ", "jre" to "ජ්‍රෙ", "jree" to "ජ්‍රේ", "jro" to "ජ්‍රො", "jroo" to "ජ්‍රෝ", "jrE" to "ජ්‍රෛ", "jau" to "ජෞ",
        "t" to "ත්", "ta" to "ත", "tA" to "තැ", "tAa" to "තෑ", "ti" to "ති", "tii" to "තී", "tu" to "තු", "tuu" to "තූ", "te" to "තෙ", "tee" to "තේ", "tY" to "ත්‍ය්", "tYa" to "ත්‍ය", "to" to "තො", "too" to "තෝ", "tE" to "තෛ", "tra" to "ත්‍ර", "trA" to "ත්‍රැ", "trAa" to "ත්‍රෑ", "tri" to "ත්‍රි", "trii" to "ත්‍රී", "tru" to "ත්‍රෘ", "truu" to "ත්‍රෲ", "tre" to "ත්‍රෙ", "tree" to "ත්‍රේ", "tro" to "ත්‍රො", "troo" to "ත්‍රෝ", "trE" to "ත්‍රෛ", "tau" to "තෞ",
        "d" to "ද්", "da" to "ද", "dA" to "දැ", "dAa" to "දෑ", "di" to "දි", "dii" to "දී", "du" to "දු", "duu" to "දූ", "de" to "දෙ", "dee" to "දේ", "dY" to "ද්‍ය්", "dYa" to "ද්‍ය", "do" to "දො", "doo" to "දෝ", "dE" to "දෛ", "dra" to "ද්‍ර", "drA" to "ද්‍රැ", "drAa" to "ද්‍රෑ", "dri" to "ද්‍රි", "drii" to "ද්‍රී", "dru" to "ද්‍රෘ", "druu" to "ද්‍රෲ", "dre" to "ද්‍රෙ", "dree" to "ද්‍රේ", "dro" to "ද්‍රො", "droo" to "ද්‍රෝ", "drE" to "ද්‍රෛ", "dau" to "දෞ",
        "n" to "න්", "na" to "න", "nA" to "නැ", "nAa" to "නෑ", "ni" to "නි", "nii" to "නී", "nu" to "නු", "nuu" to "නූ", "ne" to "නෙ", "nee" to "නේ", "nY" to "න්‍ය්", "nYa" to "න්‍ය", "no" to "නො", "noo" to "නෝ", "nE" to "නෛ", "nra" to "න්‍ර", "nrA" to "න්‍රැ", "nrAa" to "න්‍රෑ", "nri" to "න්‍රි", "nrii" to "න්‍රී", "nru" to "න්‍රෘ", "nruu" to "න්‍රෲ", "nre" to "න්‍රෙ", "nree" to "න්‍රේ", "nro" to "න්‍රො", "nroo" to "න්‍රෝ", "nrE" to "න්‍රෛ", "nau" to "නෞ",
        "p" to "ප්", "pa" to "ප", "pA" to "පැ", "pAa" to "පෑ", "pi" to "පි", "pii" to "පී", "pu" to "පු", "puu" to "පූ", "pe" to "පෙ", "pee" to "පේ", "pY" to "ප්‍ය්", "pYa" to "ප්‍ය", "po" to "පො", "poo" to "පෝ", "pE" to "පෛ", "pra" to "ප්‍ර", "prA" to "ප්‍රැ", "prAa" to "ප්‍රෑ", "pri" to "ප්‍රි", "prii" to "ප්‍රී", "pru" to "ප්‍රෘ", "pruu" to "ප්‍රෲ", "pre" to "ප්‍රෙ", "pree" to "ප්‍රේ", "pro" to "ප්‍රො", "proo" to "ප්‍රෝ", "prE" to "ප්‍රෛ", "pau" to "පෞ",
        "b" to "බ්", "ba" to "බ", "bA" to "බැ", "bAa" to "බෑ", "bi" to "බි", "bii" to "බී", "bu" to "බු", "buu" to "බූ", "be" to "බෙ", "bee" to "බේ", "bY" to "බ්‍ය්", "bYa" to "බ්‍ය", "bo" to "බො", "boo" to "බෝ", "bE" to "බෛ", "bra" to "බ්‍ර", "brA" to "බ්‍රැ", "brAa" to "බ්‍රෑ", "bri" to "බ්‍රි", "brii" to "බ්‍රී", "bru" to "බෘ", "bruu" to "බෲ", "bre" to "බ්‍රෙ", "bree" to "බ්‍රේ", "bro" to "බ්‍රො", "broo" to "බ්‍රෝ", "brE" to "බ්‍රෛ", "bau" to "බෞ",
        "m" to "ම්", "ma" to "ම", "mA" to "මැ", "mAa" to "මෑ", "mi" to "මි", "mii" to "මී", "mu" to "මු", "muu" to "මූ", "me" to "මෙ", "mee" to "මේ", "mY" to "ම්‍ය්", "mYa" to "ම්‍ය", "mo" to "මො", "moo" to "මෝ", "mE" to "මෛ", "mra" to "ම්‍ර", "mrA" to "ම්‍රැ", "mrAa" to "ම්‍රෑ", "mri" to "ම්‍රි", "mrii" to "ම්‍රී", "mru" to "ම්‍රෘ", "mruu" to "ම්‍රෲ", "mre" to "ම්‍රෙ", "mree" to "ම්‍රේ", "mro" to "ම්‍රො", "mroo" to "ම්‍රෝ", "mrE" to "ම්‍රෛ", "mau" to "මෞ",
        "y" to "ය්", "ya" to "ය", "yA" to "යැ", "yAa" to "යෑ", "yi" to "යි", "yii" to "යී", "yu" to "යු", "yuu" to "යූ", "ye" to "යෙ", "yee" to "යේ", "yo" to "යො", "yoo" to "යෝ", "yE" to "යෛ", "yau" to "යෞ",
        "r" to "ර්", "ra" to "ර", "rA" to "රැ", "rAa" to "රෑ", "ri" to "රි", "rii" to "රී", "ru" to "රු", "ruu" to "රූ", "re" to "රෙ", "ree" to "රේ", "ro" to "රො", "roo" to "රෝ", "rE" to "රෛ", "rau" to "රෞ",
        "l" to "ල්", "la" to "ල", "lA" to "ලැ", "lAa" to "ලෑ", "li" to "ලි", "lii" to "ලී", "lu" to "ලු", "luu" to "ලූ", "le" to "ලෙ", "lee" to "ලේ", "lo" to "ලො", "loo" to "ලෝ", "lE" to "ලෛ", "lau" to "ලෞ",
        "v" to "ව්", "va" to "ව", "vA" to "වැ", "vAa" to "වෑ", "vi" to "වි", "vii" to "වී", "vu" to "වු", "vuu" to "වූ", "ve" to "වෙ", "vee" to "වේ", "vo" to "වො", "voo" to "වෝ", "vE" to "වෛ", "vau" to "වෞ",
        "s" to "ස්", "sa" to "ස", "sA" to "සැ", "sAa" to "සෑ", "si" to "සි", "sii" to "සී", "su" to "සු", "suu" to "සූ", "se" to "සෙ", "see" to "සේ", "sY" to "ස්‍ය්", "sYa" to "ස්‍ය", "so" to "සො", "soo" to "සෝ", "sE" to "සෛ", "sra" to "ස්‍ර", "srA" to "ස්‍රැ", "srAa" to "ස්‍රෑ", "sri" to "ස්‍රි", "srii" to "ස්‍රී", "sru" to "ස්‍රෘ", "sruu" to "ස්‍රෲ", "sre" to "ස්‍රෙ", "សree" to "ස්‍රේ", "sro" to "ස්‍රො", "sroo" to "ස්‍රෝ", "srE" to "ස්‍රෛ", "sau" to "සෞ",
        "h" to "හ්", "ha" to "හ", "hA" to "හැ", "hAa" to "හැෑ", "hi" to "හි", "hii" to "හී", "hu" to "හු", "huu" to "හූ", "he" to "හෙ", "hee" to "හේ", "hY" to "හ්‍ය්", "hYa" to "හ්‍ය", "ho" to "හො", "hoo" to "හෝ", "hE" to "හෛ", "hra" to "හ්‍ර", "hrA" to "හ්‍රැ", "hrAa" to "හ්‍රෑ", "hri" to "හ්‍රි", "hrii" to "හ්‍රී", "hru" to "හෘ", "hruu" to "හෲ", "hre" to "හ්‍රෙ", "hree" to "හ්‍රේ", "hro" to "හ්‍රො", "hroo" to "හ්‍රෝ", "hrE" to "හ්‍රෛ", "hau" to "හෞ",
        "a" to "අ", "aa" to "ආ", "A" to "ඇ", "Aa" to "ඈ", "i" to "ඉ", "ii" to "ඊ", "u" to "උ", "uu" to "ඌ", "e" to "එ", "ee" to "ඒ", "E" to "ඓ", "o" to "ඔ", "oo" to "ඕ", "O" to "ඖ"
    )

    fun translate(input: String): String {
        return mapping[input] ?: input
    }
}
